name: Deployment Workflow
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Git
        uses: actions/checkout@v4

      - name: Configure Git
        run: |
          git config --global user.email github-actions@github.com
          git config --global user.name github-actions

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          registry-url: 'https://registry.npmjs.org'
          node-version-file: '.nvmrc'

      - name: Cache node modules
        id: cache-nodemodules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        if: steps.cache-nodemodules.outputs.cache-hit != 'true'
        shell: bash
        run: npm i

      - name: Run tests
        run: npm run test:ci

      - name: Build
        run: npm run build

      - name: Publish
        run: |
          echo "src/" >> .npmignore
          npm config set //registry.npmjs.org/:_authToken=${{ secrets.NPM_ACCESS_TOKEN }}
          npm publish

      - name: Tag
        shell: bash
        run: |
          tag_version=$(jq -er '.version' package.json)
          git tag -a v"${tag_version}" -m "Release v${tag_version}"
          git push --tags
